### PR TITLE
WIP - fixing tests

### LINKED ISSUE #642: Fix tests and all automations
- [ ] Module tests: x/compute, x/registration, x/tokenswap ...
- [ ] Sanity bash & js tests
- [ ] Automation tests - Azure pipline, ..

### PR DESCRIPTION
**Pull request by reuvenpo**
This PR fixes the various tests in our codebase, making them work with the stargate changes.
closes #642.

NOTE: This is still very much a work in progress. As long as this note is here, the PR should not be merged.

### CODE REVIEW

File: x/compute/internal/keeper/keeper.go [hunk 1]
```diff
@@ -317,7 +317,7 @@ func (k Keeper) Instantiate(ctx sdk.Context, codeID uint64, creator /* , admin *
 	instance := types.NewContractInfo(codeID, creator /* admin, */, label, createdAt)
 	store.Set(types.GetContractAddressKey(contractAddress), k.cdc.MustMarshalBinaryBare(&instance))
 
-	fmt.Printf("Storing key: %s for account %s\n", key, contractAddress)
+	fmt.Printf("Storing key: %v for account %s\n", key, contractAddress)
```
Comment (kucharskim) [inline x/compute/internal/keeper/keeper.go:320]: :heart:
